export class zomato {
  menu = [
    {
      category: 'veg',
      starter: [
        { name: 'Paneer Tikka', price: 100 },
        { name: 'Aloo Tikki', price: 80 },
        { name: 'Veg Manchurian', price: 90 },
        { name: 'Corn Cutlet', price: 90 },
        { name: 'Hara Bhara Kebab', price: 90 },
        { name: 'Onion Bhaji', price: 90 },
        { name: 'Mushroom Tikka', price: 90 },
        { name: 'Papdi Chaat', price: 90 },
        { name: 'Veg Seekh Kebab', price: 90 },
        { name: 'Samosa', price: 90 },
      ],
      mainCourse: [
        { name: 'Vegetable Biryani', price: 100 },
        { name: 'Palak Paneer', price: 200 },
        { name: 'Chole Bhature', price: 100 },
        { name: 'Kadai Vegetable', price: 100 },
        { name: 'Dal Makhani', price: 120 },
        { name: 'Paneer Butter Masala', price: 130 },
        { name: 'Veg Kofta Curry', price: 120 },
        { name: 'Aloo Gobi', price: 100 },
        { name: 'Baingan Bharta', price: 150 },
        { name: 'Matar Paneer', price: 100 },
      ],
      dessert: [
        { name: 'Gulab Jamun', price: 50 },
        { name: 'Rasgulla', price: 60 },
        { name: 'Coconut Ladoo', price: 50 },
        { name: 'Jalebi', price: 30 },
        { name: 'Kheer', price: 60 },
        { name: 'Badam Halwa', price: 50 },
        { name: 'Rasmalai', price: 50 },
        { name: 'Moong Dal Halwa', price: 50 },
        { name: 'Shahi Tukda', price: 40 },

        { name: 'ladoo', price: 80 },
      ],
    },
    {
      category: 'non-veg',
      starter: [
        { name: 'Chicken Lollipop', price: 100 },
        { name: 'Tandoori Chicken', price: 150 },
        { name: 'Butter Garlic Prawns', price: 90 },
        { name: 'Chicken Reshmi Kebab', price: 80 },
        { name: 'Lamb Chops', price: 70 },
        { name: 'Chicken Tikka', price: 100 },
        { name: 'Chicken 65', price: 80 },
        { name: 'Fish Fry', price: 90 },
        { name: 'Egg Pakora', price: 90 },
        { name: 'Prawn Tempura', price: 100 },
      ],
      mainCourse: [
        { name: 'Chicken Tikka Masala', price: 100 },
        { name: 'Fish Curry', price: 90 },
        { name: 'Mutton Rogan Josh', price: 100 },
        { name: 'Chicken Biryani', price: 120 },
        { name: 'Egg Curry', price: 120 },
        { name: 'Butter Chicken', price: 110 },
        { name: 'Prawn Curry', price: 130 },
        { name: 'Chicken Korma', price: 150 },
        { name: 'Keema Matar', price: 120 },
        { name: 'Lamb Biryani', price: 130 },
      ],
      dessert: [
        { name: 'Shahi Tukda', price: 100 },

        'Phirni',
        'Badam Kheer',
        'Lab-e-Shireen',
        'Saffron Phirni',
        'Angoori Rabdi',
        'Mango Kulfi',
        'Falooda',
        'Gulab Phirni',
        'Anjeer Halwa',
      ],
    },
    {
      category: 'vegan',
      starter: [
        { name: 'Vegan Spring Rolls', price: 100 },
        { name: 'Crispy Zucchini Fritters', price: 150 },
        { name: 'Stuffed Grape Leaves (Dolma)', price: 70 },
        { name: 'Vegan Bruschetta with Tomatoes and Basil', price: 80 },
        { name: 'Vegan Buffalo Cauliflower Wings', price: 100 },
        { name: 'Guacamole with Tortilla Chips', price: 120 },
        { name: 'Vegan Sushi Rolls', price: 140 },
        { name: 'Spicy Roasted Chickpeas', price: 80 },

        { name: 'Sweet Potato Bites', price: 70 },
        { name: 'Vegan Spinach and Artichoke Dip', price: 90 },
      ],
      mainCourse: [
        'Vegan Chickpea Curry',
        'Lentil and Vegetable Stew',
        'Vegan Mushroom Risotto',
        'Quinoa and Vegetable Stir-Fry',
        'Vegan Pad Thai',
        'Roasted Vegetable and Hummus Wrap',
        'Vegan Spaghetti Bolognese',
        'Vegan Chickpea and Spinach Stew',
        'Vegan Eggplant Parmesan',
        'Sweet Potato and Black Bean Enchiladas',
      ],
      dessert: [
        'Vegan Chocolate Cake',
        'Vegan Vanilla Cupcakes',
        'Dairy-Free Chocolate Chip Cookies',
        'Vegan Chocolate Avocado Mousse',
        'Vegan Banana Bread',
        'Vegan Coconut Ice Cream',
        'Vegan Berry Sorbet',
        'Vegan Apple Crisp',
        'Vegan Lemon Bars',
        'Vegan Peanut Butter Bliss Balls',
      ],
    },
  ];
}
